language: swift
osx_image: xcode9
script:
- swift package generate-xcodeproj --enable-code-coverage
- xcodebuild -scheme kreds-Package -enableCodeCoverage YES build test
after_success:
- bash <(curl -s https://codecov.io/bash)
