language: swift
osx_image: xcode9
script:
- swift package generate-xcodeproj --enable-code-coverage
- xcodebuild -scheme Kreds-Package -enableCodeCoverage YES test | xcpretty
after_success:
- bash <(curl -s https://codecov.io/bash)
