os:
  - osx
language: objective-c
env:
  - TOOLCHAINS=swift
sudo: required
dist: trusty
osx_image: xcode9.0
script:
  - swift build #Builds the dependencies
  - swift test #Tests whatever is inside the Test folder
notifications:
  email:
    on_success: never
    on_failure: change
