os: osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.0
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift build #Builds the dependencies
  - swift test #Tests whatever is inside the Test folder
